### PR TITLE
Fixed functionality where home page can send information to donation page

### PR DESCRIPTION
**Pull request by JAVillarino**
Fixed functionality where home page properly routes to donation page, and displays correct data.

Still need to work on browser back arrow.

### CODE REVIEW

**Comment by KataTech** [comment]
@JAVillarino  can you add a screenshot of what I am supposed to be seeing? a short video or bullet point instruction for what steps I should follow to test this can work too

**Review by KataTech — CHANGES_REQUESTED** [review]
Please include expected behavior and how to verify! Thanks!

**Comment by JAVillarino** [comment]
https://github.com/rice-apps/united-way/assets/104513571/4e4960c8-9e4e-4222-be3f-da44264f6155


Ignore the fact mine is white, idk what is the cause of that.

**Comment by KataTech** [comment]
Merged onto the reorganized codebase via `patch-routing` branch instead.

**Pull request closed without merging**
